version: "3"
services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend

  frontend:
    build: ./frontend
    container_name: frontend
    environment:
      - VITE_BACKEND_HOST=backend
      - VITE_BACKEND_PORT=8000
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src/:/frontend/src/
